server:
  port: 8082

spring:
  application:
    name: commerce
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:commercedatabase}
    username: ${POSTGRES_USERNAME:appuser}
    password: ${POSTGRES_PASSWORD:secret}
  cloud:
    stream:
      bindings:
        purchaseEvent:
          destination: purchase-topic
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

productapi:
  url: ${PRODUCT_API_URL:http://localhost:8888/}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: 'http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans'
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info