server:
  port: 8081

spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:inventorydatabase}
    username: ${POSTGRES_USERNAME:appuser}
    password: ${POSTGRES_PASSWORD:secret}
  flyway:
    locations: db/migration, db/data/prod
  cloud:
    function:
      definition: purchaseEvent
    stream:
      bindings:
        purchaseEvent-in-0:
          destination: purchase-topic
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: 'http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans'
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info